from pathlib import Path
from getpass import getpass

import pandas as pd
import psycopg2


PROJECT_ROOT = Path(__file__).resolve().parents[1]

PYTHON_FILE = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "customer_rfm.csv"
)


def load_python_rfm():
    """Load RFM results generated by Python."""

    df = pd.read_csv(PYTHON_FILE)

    df["Customer_ID"] = df["Customer_ID"].astype(int)

    return df[
        [
            "Customer_ID",
            "Recency",
            "Frequency",
            "Monetary",
            "R_Score",
            "F_Score",
            "M_Score",
            "Customer_Segment",
        ]
    ]


def load_postgresql_rfm():
    """Load RFM results from PostgreSQL."""

    password = getpass("PostgreSQL password: ")

    conn = psycopg2.connect(
        host="localhost",
        port=5432,
        database="RetailPulse_DB",
        user="postgres",
        password=password,
    )

    query = """
        SELECT
            customer_id,
            recency,
            frequency,
            monetary,
            r_score,
            f_score,
            m_score,
            customer_segment
        FROM customer_rfm_view
        ORDER BY customer_id;
    """

    df = pd.read_sql_query(query, conn)

    conn.close()

    df["customer_id"] = df["customer_id"].astype(int)

    df = df.rename(
        columns={
            "customer_id": "Customer_ID",
            "recency": "Recency",
            "frequency": "Frequency",
            "monetary": "Monetary",
            "r_score": "R_Score",
            "f_score": "F_Score",
            "m_score": "M_Score",
            "customer_segment": "Customer_Segment",
        }
    )

    return df


def main():

    print("Loading Python RFM...")
    python_df = load_python_rfm()

    print("Loading PostgreSQL RFM...")
    postgres_df = load_postgresql_rfm()

    print("\n--- Row Counts ---")
    print(f"Python:      {len(python_df):,}")
    print(f"PostgreSQL:  {len(postgres_df):,}")

    # Compare customer IDs
    python_ids = set(python_df["Customer_ID"])
    postgres_ids = set(postgres_df["Customer_ID"])

    print("\n--- Customer ID Comparison ---")
    print(f"Only in Python:     {len(python_ids - postgres_ids)}")
    print(f"Only in PostgreSQL: {len(postgres_ids - python_ids)}")

    # Merge
    merged = python_df.merge(
        postgres_df,
        on="Customer_ID",
        suffixes=("_Python", "_PostgreSQL"),
        how="outer",
        indicator=True,
    )

    common = merged[
        merged["_merge"] == "both"
    ].copy()

    # Compare RFM scores
    score_columns = [
        "R_Score",
        "F_Score",
        "M_Score",
    ]

    score_mismatch = common[
        (
            common["R_Score_Python"]
            != common["R_Score_PostgreSQL"]
        )
        |
        (
            common["F_Score_Python"]
            != common["F_Score_PostgreSQL"]
        )
        |
        (
            common["M_Score_Python"]
            != common["M_Score_PostgreSQL"]
        )
    ]

    print("\n--- RFM Score Comparison ---")
    print(
        f"Customers with different R/F/M scores: "
        f"{len(score_mismatch)}"
    )

    if len(score_mismatch) > 0:

        print("\nFirst mismatches:")

        print(
            score_mismatch[
                [
                    "Customer_ID",
                    "Recency_Python",
                    "Frequency_Python",
                    "Monetary_Python",
                    "R_Score_Python",
                    "R_Score_PostgreSQL",
                    "F_Score_Python",
                    "F_Score_PostgreSQL",
                    "M_Score_Python",
                    "M_Score_PostgreSQL",
                    "Customer_Segment_Python",
                    "Customer_Segment_PostgreSQL",
                ]
            ]
            .head(20)
            .to_string(index=False)
        )

    # Compare segments
    segment_mismatch = common[
        common["Customer_Segment_Python"]
        != common["Customer_Segment_PostgreSQL"]
    ]

    print("\n--- Segment Comparison ---")
    print(
        f"Customers with different segments: "
        f"{len(segment_mismatch)}"
    )

    if len(segment_mismatch) > 0:

        print("\nSegment mismatches:")

        print(
            segment_mismatch[
                [
                    "Customer_ID",
                    "R_Score_Python",
                    "F_Score_Python",
                    "M_Score_Python",
                    "Customer_Segment_Python",
                    "Customer_Segment_PostgreSQL",
                ]
            ]
            .to_string(index=False)
        )

    # Final summary
    if len(score_mismatch) == 0 and len(segment_mismatch) == 0:

        print("\n===================================")
        print("RFM MATCH: Python = PostgreSQL")
        print("===================================")

    else:

        print("\n===================================")
        print("RFM DIFFERENCES FOUND")
        print("===================================")


if __name__ == "__main__":
    main()